### ISSUE TITLE
DLRM-comms benchmark doesn't have device attribute

### ISSUE THREAD

**Issue by Sergei-Lebedev** [facebookresearch/param#12]
PyTorchNCCLBackend expects to have device attribute in commsParams (6e571faa196c8ebebc0820d552c12b3441f24b26). This is not the case for DLRM benchmark because first it doesn't have such parameter and second it passes dictionary to PyTorchNCCLBackend.
```shell
Traceback (most recent call last):
  File "./dlrm.py", line 1129, in <module>
    main()
  File "./dlrm.py", line 1125, in main
    dlrmBench.runBench(mpi_env_params, comms_world_info, args)
  File "./dlrm.py", line 1048, in runBench
    local_rank, global_rank, world_size, group, curDevice = comms_utils.get_rank_details(self.backendFuncs)
  File "/wspace/param/train/comms/pt/comms_utils.py", line 99, in get_rank_details
    curDevice = backendFuncs.get_device()
  File "/wspace/param/train/comms/pt/pytorch_nccl_backend.py", line 213, in get_device
    my_dev = torch.device(self.commsParams.device)
AttributeError: 'dict' object has no attribute 'device'
```

**Comment by kingchc** [comment]
@Sergei-Lebedev Thanks for reporting this. You're right, `device` option was added recently for `comms.py`, we will fix this for dlrm benchmark shortly.

**Comment by kingchc** [comment]
@Sergei-Lebedev could you try https://github.com/facebookresearch/param/pull/15 and see if it fixes the issue for you?

**Comment by Sergei-Lebedev** [comment]
@kingchc yes, it solves the issue, thanks for a quick fix!

**Comment by amrragab8080** [comment]
Fixed for me as well!
