### ISSUE TITLE
et_replay fails to import torch._inductor.runtime

### ISSUE THREAD

**Issue by vivekr321** [facebookresearch/param#128]
## Describe the Bug
> A clear and concise description of what the bug is.

ET replay module crashes with import error 
"et_replay/tools/et_replay.py", line 30, in <module>
    from torch._inductor.runtime.triton_heuristics import grid, split_scan_grid
ModuleNotFoundError: No module named 'torch._inductor.runtime'
"
please specify dependencies in requirement.txt 
## Steps to Reproduce
> Steps to reproduce the behavior.
> version: commit 884a1f0154a16e2c170e456f8027f2646c9108ae
https://github.com/facebookresearch/param/blob/main/et_replay/README.md
tested on torch 2.2.0

## Expected Behavior
> et_replay should replay given et_trace

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Sherry6352** [comment]
Got the similar issues:

Traceback (most recent call last):
  File "/root/miniconda3/envs/param/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/param/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data04/yuanyuanli/param/et_replay/tools/et_replay.py", line 25, in <module>
    from torch._inductor.async_compile import AsyncCompile
ModuleNotFoundError: No module named 'torch._inductor.async_compile'

Maybe in the requirement file, it is better to provide the version of the library.
