### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by PhdShi** [facebookresearch/param#60]
Hi. I am new to python and can't find any answer to this. The following is my command:
`mpirun -np 8 -N 8 ./dlrm.py --mini-batch-size 32 --num-batches 100 --arch-mlp-bot 256-256 --arch-sparse-feature-size 64 --arch-embedding-size "10000-10000-10000-10000-10000-10000-10000-10000"`
And then it's my errors: 
`File "/workspace/param/train/comms/pt/pytorch_dist_backend.py", line 709, in initialize_backend
    for pg_id, group_ranks in self.commsParams.groupRanks.items():
AttributeError: 'dict' object has no attribute 'groupRanks'`

**Comment by lw394** [comment]
I'm getting exactly the same error.
